variable "project_name" {}
variable "environment" {}
variable "vpc_name" {}
variable "cidr" {} 
variable "azs1" {}
variable "azs2" {}
variable "azs3" {}
variable "Private_subnet_1A" {}
variable "Private_subnet_1B" {}
variable "Private_subnet_2A" {}
variable "Private_subnet_2B" {}
variable "Private_subnet_3A" {}
variable "Private_subnet_3B" {}
variable "Public_subnet_1" {}
variable "Public_subnet_2" {}
variable "Public_subnet_3" {}